
CREATE TABLE markers ( 
	id INTEGER(200) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(256), lat DECIMAL(10,7) NOT NULL,
	lng DECIMAL(10,7),
	date_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP 
);